version: "3.2"
services:
  web:
    image: nginx:latest
    ports:
      - "9602:80"
    volumes:
      - ./confs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./confs/conf.d:/etc/nginx/conf.d
      - ./proxy_params:/etc/nginx/proxy_params:ro

  backend:
    image: pinyosminyos/kencleng:latest
    command: /usr/local/bin/gunicorn --access-logfile - --workers 3 --bind 0.0.0.0:8000 kencleng.wsgi:application
    volumes:
      - ./app:/var/www/kencleng
    ports:
      - '9599:8000'