# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-06 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kencleng_core', '0002_transaksi_pemilik'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaksi',
            name='pemilik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
